import { requireCurrentUser } from "@/lib/auth/session";
import { prisma } from "@/lib/prisma";
import { BreadcrumbHeader, EmptyState, PageHeader, Panel } from "@/components/ui";
import { createOfferingRequestAction } from "@/lib/offering-actions";
import { getActiveMembershipForUser } from "@/lib/membership";
import { versionBenefits } from "@/lib/membership-plan-versioning";
import { selectOfferingBenefit, type OfferingBenefit } from "@/lib/offerings";

export default async function NewOfferingPage() {
  const user = await requireCurrentUser();
  const [addresses, membership] = await Promise.all([prisma.customerAddress.findMany({ where: { userId: user.id }, orderBy: [{ isDefault: "desc" }, { createdAt: "desc" }] }), getActiveMembershipForUser(user.id)]);
  const benefits = (membership ? membership.planVersion ? versionBenefits(membership.planVersion) : membership.plan.benefits : []) as OfferingBenefit[];
  const access = selectOfferingBenefit(benefits, { type: "ACCESS", entityType: "OFFERINGS_ACCESS" });
  return <div className="grid gap-6"><BreadcrumbHeader items={[{ label: "Offerings", href: "/offerings" }, { label: "New request" }]} /><PageHeader eyebrow="Offerings to Blessings" title="Tell us what you would like to send" description="Operations reviews every request before collection. Do not send hazardous, perishable, sharp, wet, or personally sensitive items." />
    {!access ? <EmptyState title="Offerings access is not included" description="Your active membership does not currently include Offerings to Blessings access." /> : <Panel><form action={createOfferingRequestAction} className="grid gap-5"><input type="hidden" name="pickupListAmount" value="0" /><input type="hidden" name="membershipAccessRequired" value="true" /><fieldset className="grid gap-3"><legend className="font-semibold text-omd-brown">Materials</legend><label className="grid gap-1 text-sm font-semibold">Description<textarea required minLength={20} maxLength={2000} name="materialDescription" className="min-h-32 rounded-md border border-omd-sand p-3 font-normal" aria-describedby="materials-help" /></label><p id="materials-help" className="text-xs text-omd-muted">Include material, approximate quantity, condition, and any ritual context.</p><label className="grid gap-1 text-sm font-semibold">Photo links (optional)<textarea name="photoUrls" className="min-h-24 rounded-md border border-omd-sand p-3 font-normal" placeholder="One HTTPS link per line, up to five" /></label></fieldset>
    <fieldset className="grid gap-3"><legend className="font-semibold text-omd-brown">Transfer method</legend>{[["PICKUP","Pickup"],["DROP_OFF","Drop off"],["COURIER","Courier"]].map(([value,label]) => <label key={value} className="flex items-center gap-2"><input required type="radio" name="transferMethod" value={value} />{label}</label>)}<label className="grid gap-1 text-sm font-semibold">Saved pickup address<select name="addressId" className="rounded-md border border-omd-sand p-3 font-normal"><option value="">Select for pickup</option>{addresses.map((a) => <option key={a.id} value={a.id}>{a.addressLine1}, {a.city} {a.pincode}</option>)}</select></label><label className="grid gap-1 text-sm font-semibold">Courier tracking number (if already sent)<input name="courierTrackingNumber" className="rounded-md border border-omd-sand p-3 font-normal" /></label></fieldset>
    <label className="grid gap-1 text-sm font-semibold">Note for operations<textarea name="customerNote" className="min-h-20 rounded-md border border-omd-sand p-3 font-normal" /></label><label className="flex items-start gap-2 text-sm"><input required type="checkbox" className="mt-1" /><span>I confirm the materials are safe to handle and the description is accurate. Accepted requests may be cancelled before collection; consumed pickup benefits are not restored after collection begins.</span></label><button className="w-fit rounded-md bg-omd-brown px-5 py-3 font-semibold text-white">Submit for acceptance</button></form></Panel>}
  </div>;
}
