"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import type { MembershipBenefit, MembershipBenefitTarget, Prisma } from "@prisma/client";
import { selectShopClaimBenefit } from "@/lib/shop-membership";
import { prisma } from "@/lib/prisma";
import { requireCurrentUser } from "@/lib/auth/session";
import { addressSnapshotFromRecord, calculateInclusiveTax, invoiceNumberForOrder, resolveShippingSnapshot } from "@/lib/checkout-maturity";
import { getVariantStockSummary } from "@/lib/inventory";
import { getActiveMembershipForUser } from "@/lib/membership";
import { membershipBenefitMatchesTarget, membershipPeriodKey, reserveMembershipBenefit, transitionMembershipRedemption } from "@/lib/membership-entitlements";
import { versionBenefits } from "@/lib/membership-plan-versioning";
import { projectCommerceOrder } from "@/lib/customer-account";

type Benefit = MembershipBenefit & { targets?: MembershipBenefitTarget[] };
type Context = { productId: string; variantId: string; categoryId: string | null; tagIds: string[] };
async function nextOrderNumber(tx: Prisma.TransactionClient) { const date = new Date().toISOString().slice(0,10).replaceAll("-",""); const n = await tx.order.count({where:{orderNumber:{startsWith:`ODD-${date}`}}}); return `ODD-${date}-${String(n+1).padStart(5,"0")}`; }
export async function createComplimentaryProductClaimAction(formData: FormData) {
  const user = await requireCurrentUser(); const productId=String(formData.get("productId")??""); const addressId=String(formData.get("addressId")??""); const [variantId,benefitId]=String(formData.get("claimChoice")??"").split("|");
  if(!productId||!variantId||!benefitId||!addressId) throw new Error("Product, benefit, variant, and delivery address are required.");
  const order=await prisma.$transaction(async(tx)=>{
    const product=await tx.product.findFirst({where:{id:productId,status:"ACTIVE",type:"PHYSICAL"},include:{variants:{where:{id:variantId,active:true}}}}); if(!product||!product.variants[0]) throw new Error("This physical product variant is unavailable."); const variant=product.variants[0];
    const address=await tx.customerAddress.findFirstOrThrow({where:{id:addressId,tenantId:product.tenantId,userId:user.id}}); const shipping=await resolveShippingSnapshot(product.tenantId,address.pincode,tx); if(!shipping.shippingServiceable) throw new Error(shipping.shippingNote??"Delivery is unavailable for this address.");
    const stock=await getVariantStockSummary(variant.id,tx); if(stock.available<1) throw new Error("This item is out of stock. Your benefit has not been used.");
    const tags=await tx.tagRelation.findMany({where:{tenantId:product.tenantId,targetType:"PRODUCT",targetId:product.id},select:{tagId:true}}); const context={productId,variantId,categoryId:product.categoryId,tagIds:tags.map(t=>t.tagId)};
    const membership=await tx.userMembership.findFirst({where:{tenantId:product.tenantId,userId:user.id,status:"ACTIVE",startsAt:{lte:new Date()},expiresAt:{gt:new Date()}},include:{planVersion:true,plan:{include:{benefits:{include:{targets:true}}}}},orderBy:{expiresAt:"desc"}}); if(!membership) throw new Error("An active membership is required.");
    const benefits=(membership.planVersion?versionBenefits(membership.planVersion):membership.plan.benefits) as Benefit[]; const benefit=selectShopClaimBenefit(benefits,context,benefitId); if(!benefit) throw new Error("This claim no longer applies to the selected product or temple.");
    const unitPrice=Number(variant.price??product.basePrice??0); const shippingAmount=benefit.residualChargePolicy==="WAIVE_ALL"?0:shipping.shippingAmount; const orderNumber=await nextOrderNumber(tx); const tax=calculateInclusiveTax(0,Number(product.taxPercent??5));
    const created=await tx.order.create({data:{tenantId:product.tenantId,userId:user.id,orderNumber,status:shippingAmount===0?"confirmed":"payment_pending",paymentStatus:shippingAmount===0?"succeeded":"not_started",subtotalAmount:unitPrice,discountAmount:unitPrice,shippingAmount,taxAmount:0,taxableAmount:0,taxPercent:tax.taxPercent,totalAmount:shippingAmount,currency:product.currency,customerName:address.fullName,customerEmail:user.email??"",customerPhone:address.phone,shippingAddressJson:addressSnapshotFromRecord(address),shippingEstimateDays:shipping.shippingEstimateDays,shippingServiceable:true,shippingNote:shipping.shippingNote,invoiceNumber:shippingAmount===0?invoiceNumberForOrder(orderNumber):null,invoiceDate:shippingAmount===0?new Date():null,pricingSnapshotJson:{source:"MEMBERSHIP_CLAIM",subtotal:unitPrice,membershipSaving:unitPrice,shippingAmount,total:shippingAmount,benefitId,productId,variantId,tagIds:context.tagIds}}});
    const item=await tx.orderItem.create({data:{orderId:created.id,productId,variantId,titleSnapshot:product.title,skuSnapshot:variant.sku,itemType:"PRODUCT",quantity:1,unitPrice,lineTotal:unitPrice,membershipSavingAmount:unitPrice,membershipBenefitId:benefit.id,taxPercent:tax.taxPercent,taxableAmount:0,taxAmount:0,hsnCode:product.hsnCode,metadataJson:{claim:true,fulfilmentInstructions:benefit.fulfilmentInstructions,templeTagIds:context.tagIds}}});
    const redemption=await reserveMembershipBenefit({tenantId:product.tenantId,userId:user.id,userMembershipId:membership.id,benefitId:benefit.id,scope:"SHOP",idempotencyKey:`physical-claim:${membership.id}:${benefit.id}:${created.id}`,relatedType:"ORDER_ITEM",relatedId:item.id,lineKey:item.id,context,originalAmount:unitPrice,savingAmount:unitPrice,finalAmount:shippingAmount,reservationMinutes:shippingAmount===0?1440:30,metadataJson:{orderId:created.id,orderNumber,physicalClaim:true,shippingAmount}},tx); await tx.orderItem.update({where:{id:item.id},data:{membershipRedemptionId:redemption.id}});
    await tx.inventoryLedger.create({data:{tenantId:product.tenantId,productId,variantId,orderId:created.id,orderItemId:item.id,movementType:"reserved",quantity:1,reason:"Reserved for complimentary physical membership claim.",actorId:user.id}});
    if(shippingAmount===0){await tx.inventoryLedger.create({data:{tenantId:product.tenantId,productId,variantId,orderId:created.id,orderItemId:item.id,movementType:"sold",quantity:1,reason:"Confirmed complimentary physical membership claim.",actorId:user.id}}); await tx.inventoryLedger.create({data:{tenantId:product.tenantId,productId,variantId,orderId:created.id,orderItemId:item.id,movementType:"released",quantity:1,reason:"Cleared reservation after complimentary claim confirmation.",actorId:user.id}}); await transitionMembershipRedemption({tenantId:product.tenantId,idempotencyKey:redemption.idempotencyKey,toStatus:"CONSUMED",reason:"Physical claim confirmed after address and inventory reservation.",actorId:user.id},tx);}
    await tx.orderActivity.create({data:{tenantId:product.tenantId,orderId:created.id,actorId:user.id,type:"membership_physical_claim_created",message:shippingAmount===0?"Complimentary item claimed and ready for fulfilment.":"Complimentary item reserved; shipping payment is pending.",metadataJson:{benefitId,redemptionId:redemption.id}}}); return created;
  },{timeout:20000}); await projectCommerceOrder(order.id); for (const path of ["/my-benefits","/orders","/admin/orders","/admin/membership-claims"]) revalidatePath(path); redirect(`/orders/${order.id}${Number(order.totalAmount)>0?"?pay=1":""}`);
}
export async function getShopClaimOptions(userId:string,productId:string,variantId:string){const membership=await getActiveMembershipForUser(userId);if(!membership)return[];const product=await prisma.product.findUnique({where:{id:productId},select:{categoryId:true,tenantId:true}});if(!product)return[];const tags=await prisma.tagRelation.findMany({where:{tenantId:product.tenantId,targetType:"PRODUCT",targetId:productId},select:{tagId:true}});const context={productId,variantId,categoryId:product.categoryId,tagIds:tags.map(t=>t.tagId)};const benefits=(membership.planVersion?versionBenefits(membership.planVersion):membership.plan.benefits) as Benefit[];const now=new Date();const result:Benefit[]=[];for(const b of benefits.filter(b=>selectShopClaimBenefit([b],context,b.id,now))){const periodKey=membershipPeriodKey(b.usagePeriod,membership.id,now);const use=await prisma.membershipBenefitRedemption.aggregate({where:{userMembershipId:membership.id,benefitId:b.id,periodKey,OR:[{status:"CONSUMED"},{status:"RESERVED",reservationExpiresAt:{gt:now}}]},_sum:{quantity:true}});if(b.usageLimit===null||(use._sum.quantity??0)<b.usageLimit)result.push(b);}return result;}
