type BadgeTone = "neutral" | "success" | "warning" | "error" | "ops";

const labels: Record<string, string> = {
  ACTIVE: "Active",
  ADJUSTMENT: "Adjustment",
  ARCHIVED: "Archived",
  APPLICANT_ID: "Applicant ID",
  APPROVED: "Approved",
  ASTHI: "Asthi",
  ASTHI_APPLICATION: "Asthi Application",
  CANCELLED: "Cancelled",
  CANCEL: "Cancel",
  COMPLETED: "Completed",
  CONFIRMED: "Payment Confirmed",
  CONFIRM: "Confirm",
  CUSTOMER: "Customer",
  CUSTOMER_VISIBLE: "Customer Visible",
  FULL: "Full",
  GENERAL_SERVICE: "General Service",
  GENERAL_TASK: "General Task",
  GENERAL: "General",
  FULFILMENT: "Fulfilment",
  HIGH: "High",
  HOLD: "Hold",
  KUNDLI: "Kundli",
  KUNDLI_ORDER: "Kundli Order",
  KUNDLI_REPORT: "Kundli Report",
  KUNDLI_UPLOAD: "Kundli Upload",
  LOW: "Low",
  NORMAL: "Normal",
  ORDER_REQUEST: "Order Request",
  ORDER_ITEM: "Order Item",
  DETAILS_PENDING: "Details Pending",
  DRAFT: "Draft",
  DEATH_CERTIFICATE: "Death Certificate",
  DOCUMENTS_UNDER_REVIEW: "Documents Under Review",
  DOCUMENTS_VERIFIED: "Documents Verified",
  EXPIRED: "Expired",
  FAILED: "Payment Failed",
  FAMILY_PRESENT: "Family Present",
  DIGITAL_REPORT: "Digital Report",
  INACTIVE: "Inactive",
  HANDMADE_REPORT: "Handmade Report",
  INTERNATIONAL: "International / NRI",
  IN_PROGRESS: "In Progress",
  IN_STOCK: "In Stock",
  MATCHMAKING: "Kundli Matching",
  LOW_STOCK: "Low Stock",
  NOT_STARTED: "Not Started",
  OUT_OF_STOCK: "Out of Stock",
  OTHER: "Other Document",
  INTERNAL_NOTE_FILE: "Internal Note File",
  INTERNAL_ONLY: "Internal Only",
  PAYMENT_PENDING: "Payment Pending",
  PENDING: "Payment Pending",
  PENDING_REVIEW: "Pending Review",
  PENDING_UPLOAD: "Pending Upload",
  PROOF_UPLOADED: "Proof Uploaded",
  PRASAD_DISPATCH_PROOF: "Prasad Dispatch Proof",
  PUJA: "Puja",
  QUEUED: "Queued",
  REPORT_AND_CONSULTATION: "Report + Consultation",
  REPORT_READY: "Report Ready",
  REFUNDED: "Refunded",
  REFUND_PROOF: "Refund Proof",
  RELEASE: "Release",
  REJECTED: "Rejected",
  RELATION_PROOF: "Relation Proof",
  REQUESTED: "Requested",
  REUPLOAD_REQUIRED: "Reupload Required",
  REMOTE_ASSISTED: "Remote Assisted",
  RITUAL_SCHEDULED: "Ritual Scheduled",
  RITUAL_PROOF: "Ritual Proof",
  ASSIGNED: "Assigned",
  BLOCKED: "Blocked",
  CONSULTATION: "Consultation",
  CONSULTATION_SCHEDULED: "Consultation Scheduled",
  DELIVERED: "Delivered",
  EXISTING_KUNDLI: "Existing Kundli",
  SUBMITTED: "Submitted",
  SUPPORTING_DOCUMENT: "Supporting Document",
  SUPPORT: "Support",
  RISK: "Risk",
  MEMBERSHIP: "Membership",
  SETTINGS: "Settings",
  RETURN_PROOF: "Return Proof",
  SERVICE_BOOKING: "Service Booking",
  UNDER_REVIEW: "Under Review",
  UPLOADED: "Uploaded",
  URGENT: "Urgent",
  VISIBILITY_CHANGED: "Visibility Changed",
  adjustment: "Stock Adjustment",
  assignment_updated: "Assignment Updated",
  admin_role_assigned: "Admin Role Assigned",
  admin_role_removed: "Admin Role Removed",
  admin_role_removal_blocked: "Admin Role Removal Blocked",
  accepted: "Accepted",
  applicant_id_proof: "Applicant ID Proof",
  application_submitted: "Application Submitted",
  cancelled: "Cancelled",
  confirmed: "Confirmed",
  created: "Created",
  customer_internal_note_created: "Customer Internal Note Created",
  closed: "Closed",
  cancel: "Cancellation",
  damaged: "Damaged",
  death_certificate: "Death Certificate",
  delivered: "Delivered",
  document_approved: "Document Approved",
  document_archived: "Document Archived",
  document_rejected: "Document Rejected",
  document_requested: "Document Requested",
  document_reupload_required: "Document Reupload Required",
  document_review_started: "Document Review Started",
  document_uploaded: "Document Uploaded",
  document_visibility_changed: "Document Visibility Changed",
  document_verification: "Document Verification",
  expired: "Expired",
  failed: "Payment Failed",
  initial: "Opening Stock",
  missing: "Missing",
  not_available: "Not Available",
  not_started: "Not Started",
  order_cancelled: "Order Cancelled",
  order_delivered: "Order Delivered",
  order_processing: "Order Processing",
  order_ready_to_ship: "Ready to Ship",
  order_refund_requested: "Refund Requested",
  order_refunded: "Refunded",
  order_shipped: "Order Shipped",
  order_request_approved: "Request Approved",
  order_request_closed: "Request Closed",
  order_request_rejected: "Request Rejected",
  order_request_submitted: "Request Submitted",
  order_request_under_review: "Request Under Review",
  other_document: "Other Document",
  payment_cancelled: "Payment Cancelled",
  payment_confirmed: "Payment Confirmed",
  payment_failed: "Payment Failed",
  payment_pending: "Payment Pending",
  payment_succeeded: "Payment Succeeded",
  "payment.cancelled": "Payment Cancelled",
  "payment.expired": "Payment Expired",
  "payment.failed": "Payment Failed",
  "payment.started": "Payment Started",
  "payment.succeeded": "Payment Succeeded",
  pending: "Payment Pending",
  pending_upload: "Pending Upload",
  processing: "Processing",
  ready_to_ship: "Ready to Ship",
  relation_proof: "Relation Proof",
  reschedule_approved: "Reschedule Approved",
  reschedule_closed: "Reschedule Closed",
  reschedule_moved_to_queue: "Reschedule Moved to Queue",
  reschedule_priority_exception: "Priority Exception",
  reschedule_rejected: "Reschedule Rejected",
  reschedule_requested: "Reschedule Requested",
  reschedule_under_review: "Reschedule Under Review",
  refund: "Refund",
  rejected: "Rejected",
  refunded: "Refunded",
  released: "Released",
  reserved: "Reserved",
  returned: "Returned",
  return: "Return",
  SCHEDULED: "Scheduled",
  schedule_changed: "Schedule Changed",
  shipped: "Shipped",
  sold: "Sold",
  submitted: "Submitted",
  succeeded: "Paid",
  under_review: "Under Review",
  uploaded: "Uploaded",
  unfulfilled: "Awaiting Processing"
};

export function statusLabel(value: string | null | undefined) {
  if (!value) return "Not Set";
  return labels[value] ?? value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
}

export function statusTone(value: string | null | undefined): BadgeTone {
  if (!value) return "neutral";
  if (
    [
      "ACTIVE",
      "APPROVED",
      "COMPLETED",
      "CONFIRMED",
      "DOCUMENTS_VERIFIED",
      "DELIVERED",
      "IN_STOCK",
      "PROOF_UPLOADED",
      "REPORT_READY",
      "UPLOADED",
      "accepted",
      "confirmed",
      "approved",
      "delivered",
      "order_request_approved",
      "order_delivered",
      "payment_confirmed",
      "payment_succeeded",
      "processing",
      "ready_to_ship",
      "shipped",
      "succeeded"
    ].includes(value)
  ) {
    return "success";
  }
  if (
    [
      "ARCHIVED",
      "CANCELLED",
      "EXPIRED",
      "OUT_OF_STOCK",
      "FAILED",
      "REFUNDED",
      "REJECTED",
      "BLOCKED",
      "cancelled",
      "damaged",
      "expired",
      "failed",
      "missing",
      "order_cancelled",
      "payment_cancelled",
      "payment_failed",
      "rejected",
      "closed",
      "refunded"
    ].includes(value)
  ) {
    return "error";
  }
  if (
    [
      "DETAILS_PENDING",
      "DOCUMENTS_UNDER_REVIEW",
      "ASSIGNED",
      "CONSULTATION_SCHEDULED",
      "IN_PROGRESS",
      "LOW_STOCK",
      "NOT_STARTED",
      "PAYMENT_PENDING",
      "PENDING",
      "PENDING_REVIEW",
      "PENDING_UPLOAD",
      "QUEUED",
      "RITUAL_SCHEDULED",
      "SCHEDULED",
      "REQUESTED",
      "REUPLOAD_REQUIRED",
      "payment_pending",
      "pending",
      "pending_upload",
      "submitted",
      "under_review",
      "order_request_submitted",
      "order_request_under_review",
      "uploaded",
      "not_started",
      "unfulfilled"
    ].includes(value)
  ) {
    return "warning";
  }
  return "neutral";
}
